name: Build

on:
  push:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make linux
      run: make
    - uses:  actions/upload-artifact@v3.1.0
      with:
        name: linux-x64
        path: bin

  test-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make linux
      run: make
    - name: Create a big packing
      run: tools/argvtolines.sh Packings/N4096~P1e-2 1 1 1 2 | bin/jam2D -screen
    - uses:  actions/upload-artifact@v3.1.0
      with:
        name: packings-a
        path: Packings
    - name: Shear the big packing
      run: tools/argvtolines.sh Packings/N4096~P1e-2 4 1 1 0.1 1 3 | bin/jam2D -screen
    - uses:  actions/upload-artifact@v3.1.0
      with:
        name: packings-b
        path: Packings

  build-windows-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/checkout@v3
    - name: make win64
      run: make win64
    - uses:  actions/upload-artifact@v3.1.0
      with:
        name: win64
        path: bin

